bracketSpacing: false
printWidth: 100
semi: false
singleQuote: true
tabWidth: 2
trailingComma: es5
arrowParens: always
overrides:
  - files: "*.json"
    options:
      parser: "json"
  - files: "*.ts"
    options:
      parser: "typescript"