bracketSpacing: false
parser: typescript
printWidth: 80
semi: false
singleQuote: true
tabWidth: 2
trailingComma: es5
arrowParens: always
overrides:
  - files: "*.json"
    options:
      parser: "json"